name: Python CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-and-package:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:

    - name: Run Ruff Static Analysis
      run: ruff check src/unidesk/

